name: Build Linux

on:
  push:
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 平台依赖
      - run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt-get update
          sudo apt-get install xmake unzip

      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: xmake -y

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: rtd-linux
          path: ./build/bin
