name: Commit CI

on:
  push:
    paths:
      - "src/**"
      - "v3/**"
      - "include/**"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      # 平台依赖
      - run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt-get update
          sudo apt-get install xmake unzip

      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: xmake -y

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ./build/bin

  windows:
    runs-on: windows-latest
    steps:
      # setup xmake
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: xmake -y

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./build/bin
