name: Commit CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      # 平台依赖
      - run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt-get update
          sudo apt-get install xmake unzip

      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # Restore xmake
      - name: Restore
        uses: actions/cache@v3
        with:
          path: ~/.xmake
          key: ${{ runner.os }}-xmake

      - name: Build
        run: xmake -y

      # Save xmake
      - name: Save
        uses: actions/cache@v3
        with:
          path: ~/.xmake
          key: ${{ runner.os }}-xmake

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ./build/bin

  windows:
    runs-on: windows-latest
    steps:
      # setup xmake
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # Restore xmake
      - name: Restore
        uses: actions/cache@v3
        with:
          path: ~/AppData/Local/.xmake
          key: ${{ runner.os }}-xmake

      - name: Build
        run: xmake -y

      # Save xmake
      - name: Save
        uses: actions/cache@v3
        with:
          path: ~/AppData/Local/.xmake
          key: ${{ runner.os }}-xmake

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./build/bin
